# backend:
#   name: git-gateway
#   branch: main  # Ensure you're using your default branch, usually 'main' or 'master'
backend:
  name: github
  repo: nvnt-admin/nvnt-admin.github.io
  branch: main
  base_url: https://nvnt-admin.github.io/
  
display_url: https://nvnt-admin.github.io/
media_folder: "static/images"  # Media files (images) will be stored here
public_folder: "/static/images"  # URL for media files

collections:
  # Blog posts
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'short_name',
        }
      - { label: 'Categories', name: 'categories', widget: 'list', required: false } # Add categories field
      - { label: 'Tags', name: 'tags', widget: 'list', required: false } # Add tags field (as a list)
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Video', name: 'video', widget: 'file', media_folder: 'static/videos', public_folder: '/static/videos', required: false }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }

  # Personal posts
  - name: 'personal'
    label: 'Personal'
    folder: '_personal'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Video', name: 'video', widget: 'file', media_folder: 'static/videos', public_folder: '/static/videos' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'personal' }

  # Authors collection
  - name: 'authors'
    label: 'Authors'
    folder: '_authors'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Short Name', name: 'short_name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
